### ISSUE TITLE
database tasarımı

### ISSUE THREAD

**Issue by kemalkanok** [SymfonyLearning/ForBlog#3]
auth bundle içn veri tabanı tasarımı hazırlanıp sunulacak

**Comment by azizdursungoktepe** [comment]
![img_1611](https://cloud.githubusercontent.com/assets/5631572/13887828/8d1059ac-ed46-11e5-9fb4-aa68299571e6.jpg)

**Comment by kemalkanok** [comment]
Şahane ama bunu githubdan gönder :D

From:  azizdursungoktepe
Reply-To:  SymfonyLearning/ForBlog
Date:  Friday 18 March 2016 at 20:18
To:  SymfonyLearning/ForBlog
Cc:  Kemal Kanok
Subject:  Re: [ForBlog] database tasarımı (#3)
Resent-From:  <kkanok11@posta.pau.edu.tr>

**Comment by zerrinbds** [comment]
hep beraber düsündük ve github n burası olduguna karar verdik :) xD

**Comment by kemalkanok** [comment]
uygundur
