### ISSUE TITLE
şifremi unuttum ekran tasarımı

### ISSUE THREAD

**Issue by kemalkanok** [SymfonyLearning/ForBlog#6]

**Comment by azizdursungoktepe** [comment]
![img_1615](https://cloud.githubusercontent.com/assets/5631572/13888080/0cbdd9b2-ed48-11e5-8869-3bd48c469d6c.jpg)

**Comment by kemalkanok** [comment]
Isterseniz ofise gelin az bir işim kaldı

From:  azizdursungoktepe
Reply-To:  SymfonyLearning/ForBlog
Date:  Friday 18 March 2016 at 20:29
To:  SymfonyLearning/ForBlog
Cc:  Kemal Kanok
Subject:  Re: [ForBlog] şifremi unuttum ekran tasarımı (#6)
Resent-From:  <kkanok11@posta.pau.edu.tr>
