### ISSUE TITLE
Kullanıcı kayıt sistemi

### ISSUE THREAD

**Issue by kemalkanok** [SymfonyLearning/ForBlog#8]
kullanıcının email ve şifresini alıp veritabanında barındırma işlemi

**Comment by surasanal** [comment]
Bi önceki güncellemede buton kısmını düzelmişti ama bootstrap ekledikten sonra yine çalışmıyor.

**Comment by surasanal** [comment]
Bide bootstrap validation kısmını aktif hale getiremedim.

**Comment by kemalkanok** [comment]
şu anda validation kısmının php tabanlı olması yeterli 
```
<<<<<<< Updated upstream
            echo "Hata";
=======
            echo "Hata";
>>>>>>> Stashed changes
```
bunlar barındığı için hata olabilir :)

**Comment by surasanal** [comment]
Güncellendi #8
